version: "3.9"

services:
  api:
    build: .
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data #ajout important pour persistence

  test:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    command: ["sh", "-c", "sleep 6 && pytest"]

#sert à déclarer un volumes nommé pgdata (utilisé plus haut)
volumes:
  pgdata:
